baseUrl: http://example.com:4555 # The Tomatic instance url base for the cli tools to access the API
hangoutChannel: 'EwCesKUaJZ1yCpn3R4J4AaABAQ' # the channel id used to warn operators
# Drive spreadsheet with input information to compute scheduling
documentDrive: Tomatic Control
fullCarregaIdeal: "Ideal Load"
idealLoadNamesRange: idealload_names
idealLoadValuesRange: idealload_values
leavesSheet: Leaves
monitoringFile: taula.html
nTelefons: 4
diesCerca: ['dm', 'dv', 'dx', 'dl', 'dj',] # Harder to fit, first
diesVisualitzacio: ['dl','dm','dx','dj','dv']

hours:  # La darrera es per tancar
- '09:00'
- '10:15'
- '11:30'
- '12:45'
- '14:00'
mostraCami:  false   # mostra el cami de cerca que va fent (molt lent)
maximCamiAMostrar: 60   # fins a quin nivell mostra el camí de cerca
aleatori: true   # si l'ordre de provar entre els companys a cada casella es aleatori
backtrackDepth: 10000   # Comprovacions a una via abans de rendir-se i provar una altra
costLimit: 100   # No et molestis en comprobar solucions que no sigui millors
descartaNoPrometedores: true # Pot descartar solucions bones, pero agilitza molt
deixaEsmorzar: true     # Si hom ha de tenir una de les hores d'esmorzar lliures
noVolenEsmorzar:
- david
maximPerTaula: 2   # maxim nombre de telefons simultanis a una mateixa taula
maximsT1PerDia: 1   # maxim nombre de torns primaris diaris per a una persona
maximHoresDiariesGeneral: 2  # maxim nombre de torns diaris per una persona
maximHoresDiaries:   # excepcions al maximHoresDiariesGeneral
   manel: 2
   xuanin: 2
   silvia: 2
costHoresDiscontinues: 40   # Per cada salt que te una persona entre dos hores de telefon un mateix dia
costHoresConcentrades: 1   # Es multiplica per n·(n-1)/2 on n es el nombre d'hores diaries d'una mateixa persona
costTaulaSorollosa: 5   # Es multiplica per n·(n-1)/2 on n es el nombre de telefons simultanis a una taula
costHoraNoDesitjada: 0   # No implementat
sempreUnLliure: {}
randomColors: false # Si vols generar colors aleatoris o fer cas de 'colors'

forced:
  [dl, 1, 4]: ningu
  [dl, 2, 4]: ningu
  [dm, 1, 4]: ningu
  [dm, 2, 4]: ningu
  [dx, 1, 4]: ningu
  [dx, 2, 4]: ningu
  [dj, 1, 4]: ningu
  [dj, 2, 4]: ningu
  [dv, 1, 4]: ningu
  [dv, 2, 4]: ningu


