fullIndisponibilitats: Reunions i altres afers
fullCarrega_antic: o9rxhxk  #Càrrega setmanal de telèfon
fullCarrega: opm82es  #Carrega_5t_telefon
intervalCarrega: carrega{:02d}{:02d}{:02d}
monitoringFile: taula.html
nTelefons: 5
diesCerca:
- dm
- dv
- dx
- dl
- dj
diesVisualitzacio:
- dl
- dm
- dx
- dj
- dv
hours:
- 09:00
- '10:15'
- '11:30'
- '12:45'
- '14:00'
mostraCami: false
maximCamiAMostrar: 60
aleatori: true
backtrackDepth: 10000
costLimit: 200
descartaNoPrometedores: true
deixaEsmorzar: true
noVolenEsmorzar:
- david
- ningu
maximPerTaula: 2
maximsT1PerDia: 1
maximHoresDiariesGeneral: 2
maximHoresDiaries:
  ningu: 4
costHoresDiscontinues: 40
costHoresConcentrades: 1
costTaulaSorollosa: 5
costHoraNoDesitjada: 0
taules:
  marc: 10
  joan: 5
  mariona: 0
  eduard: 8
  pere: -1
  david: 2
  carles: 8
  monica: 4
  judith: 4
  maite: 9
  erola: 1
  sergi: 3
  judit: 13
  joanb: 4
  marta: 5
  yaiza: 7
  victor: 8
  silvia: 13
  ana: 5
  gabriel: 6
  manel: 1
  tania: 3
  lucia: 3
  vic: 7
  maria: 1
  pau: 1
  carol: 5
  viktu: -1
  albert: 6
  oriol: -1
  fran: 2
  miguelanxo: 9
  belen: 12
  fcasadella: 10
  gijsbert: 12
  nuri: 12
  fcots: 11
  annarodon: 11
  alberto: 2
  juanpe: -1
  ningu: -1
  olga: -1
  mar: -1
  joanm: 7
  roger: 5
  vane: -1
  eloi: 6
  annab: -1
  vero: 6
  projectes: 12
  jordi: 2
  xavi: -1
  joana: 2
sempreUnLliure: {}
randomColors: false
colors:
  marc: fbe8bc
  eduard: d8b9c5
  pere: f200ff
  david: ffb300
  carles: c98e98
  marta: eb9481
  monica: 7fada0
  yaiza: ffffff
  erola: 876dd8
  manel: ff0084
  tania: c8abf4
  judit: e781e8
  silvia: 8097fa
  joan: fae080
  ana: ff6600
  victor: ff3233
  judith: 00ff00
  lucia: 9f24c2
  sergi: 8cf2df
  vic: 164aff
  mariona: '813400'
  gabriel: ffff00
  maite: 007877
  ningu: ffffff
  joanb: 8af47d
  maria: 00594d
  pau: e6f214
  carol: 94c703
  undefined: ddeeff
  viktu: ddeeff
  albert: ddeeff
  oriol: a52513
  fran: 621bf1
  miguelanxo: bdaa1c
  belen: 2892ff
  fcasadella: 10ee30
  gijsbert: 00eeff
  nuri: 17ef6f
  fcots: ff5a60
  annarodon: 009e7d
  alberto: 0074f0
  juanpe: ddeeff
  olga: ddeeff
  mar: 00fcff
  joanm: 2d93f2
  roger: 367c0f
  vane: bd00ff
  eloi: 9baec4
  annab: c1f3d7
  vero: ff0048
  projectes: ffffe7
  jordi: 2756ff
  xavi: ddeeff
  joana: c9ec80
extensions:
  marta: 3040
  monica: '3041'
  manel: '3042'
  erola: '3043'
  yaiza: '3044'
  eduard: '3182'
  marc: '3046'
  judit: '3047'
  tania: '3183'
  carles: '3045'
  pere: '3052'
  fran: 3008
  david: 3054
  silvia: '3055'
  joan: 3056
  judith: '3057'
  ana: '3181'
  victor: 3182
  lucia: '3184'
  vic: 3185
  sergi: '3186'
  maite: '3187'
  gabriel: 3188
  mariona: '3189'
  joanb: 3195
  maria: '3039'
  pau: '3048'
  carol: 3049
  viktu: '3006'
  albert: 3038
  oriol: '3089'
  miguelanxo: 3194
  belen: '3007'
  fcasadella: '3002'
  gijsbert: '3003'
  nuri: '3889'
  fcots: '0000'
  annarodon: '3196'
  alberto: 3011
  juanpe: '0000'
  olga: '3088'
  mar: '3087'
  joanm: '3086'
  roger: '3085'
  vane: '3084'
  eloi: '3083'
  annab: '3082'
  vero: '3081'
  jordi: '3004'
  xavi: '3009'
  joana: '4001'
names:
  silvia: Sílvia
  monica: Mònica
  tania: Tània
  cesar: César
  victor: VíctorNA
  lucia: Lucía
  joanb: JoanB
  ningu: '-'
  joan: Joan
  carol: Càrol
  miguelanxo: MiguelAnxo
  belen: Belén
  fcasadella: FrancescCasadellà
  fcots: FrancescCots
  annarodon: AnnaRodon
  juanpe: Juanpe
  joanm: Joan Marquès
  annab: Anna B
  eloi: 'Eloi '
  projectes: PROJECTES
  jordi: Jordi Pons
  xavi: XaviDolz
forced: {}
also_commented_forced:
  ? - dl
    - 1
    - 5
  : ningu
  ? - dl
    - 2
    - 5
  : ningu
  ? - dl
    - 3
    - 5
  : ningu
  ? - dl
    - 4
    - 5
  : ningu
commented_forced:
  ? - dl
    - 1
    - 4
  : ningu
  ? - dl
    - 2
    - 4
  : ningu
  ? - dm
    - 1
    - 4
  : ningu
  ? - dm
    - 2
    - 4
  : ningu
  ? - dx
    - 1
    - 4
  : ningu
  ? - dx
    - 2
    - 4
  : ningu
  ? - dj
    - 1
    - 4
  : ningu
  ? - dj
    - 2
    - 4
  : ningu
  ? - dv
    - 1
    - 4
  : ningu
  ? - dv
    - 2
    - 4
  : ningu
