baseUrl: http://192.168.35.244:4555
documentDrive: Quadre de Vacances
fullIndisponibilitats: Reunions i altres afers
fullCarrega_4: o9rxhxk
fullCarrega_5: opm82es
fullCarrega: om1qfyn
intervalCarrega: carrega{:02d}{:02d}{:02d}
monitoringFile: taula.html
nTelefons: 6
diesCerca:
- dl
- dm
- dx
- dj
- dv
diesVisualitzacio:
- dl
- dm
- dx
- dj
- dv
hours:
- 09:00
- '10:15'
- '11:30'
- '12:45'
- '14:00'
pruneRedundant: true
newYearHack: false
ignoreOptionalAbsences: false
mostraCami: false
maximCamiAMostrar: 60
aleatori: true
stopPenalty: 0
backtrackDepth: 10000000000
maxNodesToPersevere: 100000
costLimit: 200
descartaNoPrometedores: true
deixaEsmorzar: true
noVolenEsmorzar:
- david
- ningu
maximPerTaula: 2
maximsT1PerDia: 1
maximHoresDiariesGeneral: 2
maximHoresDiaries:
  ningu: 10
costHoresDiscontinues: 40
costHoresConcentrades: 1
costTaulaSorollosa: 5
costHoraNoDesitjada: 0
taules:
  marc: 16
  joan: 5
  mariona: 17
  eduard: 7
  pere: 99
  david: 5
  carles: 8
  monica: 15
  judith: 14
  maite: 1
  erola: 12
  sergi: 19
  judit: 13
  joanb: 14
  marta: 15
  yaiza: 15
  victor: 7
  silvia: 13
  ana: 18
  gabriel: 9
  manel: 12
  tania: 7
  lucia: 3
  vic: 19
  maria: 12
  pau: 12
  carol: 18
  viktu: -1
  albert: 17
  oriol: 10
  fran: 10
  juanpe: 0
  belen: 3
  fcasadella: 8
  gijsbert: 16
  nuri: 3
  fcots: 16
  annarodon: 16
  alberto: 10
  ningu: -1
  ningu2: -1
  olga: -1
  mar: 19
  joanm: 6
  roger: 9
  vane: 17
  eloi: 17
  annab: -1
  vero: 9
  projectes: 12
  jordi: 2
  xavi: -1
  joana: 2
  rogerlf: 14
  gemma: 19
  aram: -1
  benjami: 99
  guifre: 8
  nuria: 99
  carme: 99
  merce: 13
  albertg: 99
  adria: 13
  monicag: 99
  otilia: 17
  contestado: 99
  alex: 99
  javi: 99
  albertsimo: 99
  clara: 99
  jaume: 99
  davids: 99
  hermigg: 99
  cire: 99
  francesc: 99
  berta: 99
  yolanda: 99
  joel: 99
sempreUnLliure: {}
groups:
  ramat:
  - judit
  - judith
  - javier
  - marc
  - joan
  - mariona
  - eduard
  - pere
  - david
  - carles
  - monica
  - judith
  - maite
  - erola
  - sergi
  - judit
  - joanb
  - marta
  - yaiza
  - victor
  - silvia
  - ana
  - gabriel
  - manel
  - tania
  - lucia
  - vic
  - maria
  - pau
  - carol
  - albert
  - oriol
  - fran
  it:
  - alberto
  - david
  - fran
  - oriol
  - juanpe
  - jordi
  - xavi
  - benjami
  - davids
  - joana
  infern:
  - monica
  - carles
  - manel
  - marc
  - marta
  balneari:
  - aram
  - olga
  - joanm
  - mariona
  - victor
  - eloi
  - eduard
  - albertg
  - albert
  - carol
  - gabriel
  - vero
  - nuria
  - otilia
  - guifre
  - annab
  - monicag
  - roger
  - vane
  casademont:
  # Roger Lapeña, Lucía, Adrià, Silvia, Judith, Carme, Erola, Mar, Joan B, Maria, Sergi, Yaiza, Gemma, Pau, Tània, Juan U. Vic
  - rogerlf
  - lucia
  - adria
  - silvia
  - judith
  - carme
  - erola
  - mar
  - joanb
  - maria
  - sergi
  - yaiza
  - gemma
  - pau
  - tania
  - joan
  - vic
maxPhoningInGroup:
  infern: 2
  casademont: 4
  balneari: 4
minIdleInGroup:
  it: 4
randomColors: false
colors:
  marc: fbe8bc
  eduard: d8b9c5
  pere: ddeeff
  david: ffb300
  carles: c98e98
  marta: eb9481
  monica: 7fada0
  yaiza: ffffff
  erola: 876dd8
  manel: ff0084
  tania: c8abf4
  judit: e781e8
  silvia: 8097b8
  joan: fae080
  ana: ff6600
  victor: ff3233
  judith: 00ff00
  lucia: 9f24c2
  sergi: 8cf2df
  vic: 164aff
  mariona: '813400'
  gabriel: ffff00
  maite: 007877
  ningu: ffffff
  joanb: 8af47d
  maria: 00594d
  pau: e6f214
  carol: 94c703
  undefined: ddeeff
  viktu: ddeeff
  albert: f4f4f4
  oriol: a52513
  fran: 621bf1
  juanpe: ddeeff
  belen: 2892ff
  fcasadella: 10ee30
  gijsbert: 00adff
  nuri: 17ef6f
  fcots: ff5a60
  annarodon: 009e7d
  alberto: 0074f0
  olga: ddeeff
  mar: 00ffff
  joanm: 2d93f2
  roger: 367c0f
  vane: bd00ff
  eloi: 9baec4
  annab: c1f3d7
  vero: ff0048
  projectes: ffffe7
  jordi: 2756ff
  xavi: ddeeff
  joana: c9ec80
  rogerlf: 00517d
  gemma: a6ba8c
  aram: 614d02
  benjami: 53ff14
  guifre: ff000e
  nuria: 00662a
  carme: 0000ff
  merce: f5447f
  albertg: fcdc05
  adria: b68f2f
  monicag: f44c3b
  otilia: 96b0ff
  contestado: 333c3a
  alex: ce6108
  javi: 79eeff
  albertsimo: cc00ff
  clara: 602fa7
  jaume: 74eb79
  cesar: ffffee
  davids: d8863d
  hermigg: ddbdf1
  cire: 994a00
  francesc: dcf664
  berta: ddeeff
  yolanda: ddeeff
  joel: 00797c
notoi_ids:
  marta: 1
  albertg: null
  yaiza: null
  vero: null
  benjami: null
  eduard: null
  tania: null
  victor: null
  albert: null
  judith: null
  manel: null
  maite: null
  eloi: null
  erola: null
  lucia: null
  davids: null
  mar: null
  gemma: null
  vic: null
  sergi: null
  juanpe: null
  hermigg: 2406
  cire: 1007
  francesc: 1718
  jaume: null
  berta: null
  yolanda: null
  pere: null
  joel: null
extensions:
  marta: '3040'
  monica: '3041'
  manel: '3042'
  erola: '3043'
  yaiza: '3044'
  eduard: '3051'
  marc: '3046'
  judit: '3047'
  tania: '3183'
  carles: '3045'
  pere: '3062'
  fran: '3008'
  david: '3054'
  silvia: '3055'
  joan: '3056'
  judith: '3057'
  ana: '3181'
  victor: '3182'
  lucia: '3184'
  vic: '3185'
  sergi: '3186'
  maite: '3187'
  gabriel: '3188'
  mariona: '3189'
  joanb: '3195'
  maria: '3039'
  pau: '3048'
  carol: '3049'
  viktu: '3006'
  albert: '3038'
  oriol: '3089'
  juanpe: '3194'
  belen: '3385'
  fcasadella: '3002'
  gijsbert: '3003'
  nuri: '3889'
  fcots: '3015'
  annarodon: '3197'
  alberto: '3011'
  olga: '3088'
  mar: '3087'
  joanm: '3086'
  roger: '3085'
  vane: '3084'
  eloi: '3083'
  annab: '3082'
  vero: '3081'
  jordi: '3004'
  xavi: '3009'
  joana: '4001'
  rogerlf: '2902'
  gemma: '2903'
  aram: '2905'
  benjami: '3012'
  guifre: '2911'
  nuria: '2909'
  carme: '2904'
  merce: '2908'
  albertg: '2901'
  adria: '2907'
  monicag: '2906'
  otilia: '2910'
  contestado: '3193'
  alex: '3050'
  javi: '3383'
  albertsimo: '3013'
  clara: '3014'
  jaume: '3196'
  davids: '4003'
  hermigg: '2406'
  cire: '3065'
  francesc: '3017'
  berta: '3060'
  yolanda: '3061'
  joel: '3063'
names:
  silvia: Sílvia
  monica: Mònica
  tania: Tània
  cesar: César
  victor: VíctorNA
  lucia: Lucía
  joanb: JoanB
  ningu: '-'
  joan: Joan
  carol: Càrol
  juanpe: Juan Pe
  belen: Belén
  fcasadella: FrancescCasadellà
  fcots: FrancescCots
  annarodon: AnnaRodon
  joanm: JoanM
  annab: Anna B
  eloi: 'Eloi '
  projectes: PROJECTES
  jordi: JordiP
  xavi: XaviDolz
  david: David G.
  gijsbert: Salomé
  rogerlf: RogerLF
  guifre: Guifré
  merce: Mercè
  adria: Adrià
  monicag: Mònica G
  albertg: Albert GS
  albert: Albert M
  otilia: 'Otilia '
  nuria: Núria
  contestado: '>>>CONTESTADOR<<<'
  albertsimo: AlbertSi
  jaume: JaumeA
  davids: DavidS
  hermigg: Hermi
  francesc: Cesc
forced: {}
also_commented_forced:
  ? - dl
    - 1
    - 5
  : ningu
  ? - dl
    - 2
    - 5
  : ningu
  ? - dl
    - 3
    - 5
  : ningu
  ? - dl
    - 4
    - 5
  : ningu
commented_forced:
  ? - dl
    - 1
    - 4
  : ningu
  ? - dl
    - 2
    - 4
  : ningu
  ? - dm
    - 1
    - 4
  : ningu
  ? - dm
    - 2
    - 4
  : ningu
  ? - dx
    - 1
    - 4
  : ningu
  ? - dx
    - 2
    - 4
  : ningu
  ? - dj
    - 1
    - 4
  : ningu
  ? - dj
    - 2
    - 4
  : ningu
  ? - dv
    - 1
    - 4
  : ningu
  ? - dv
    - 2
    - 4
  : ningu
websocket_ip: 192.168.35.244
websocket_port: 4445
call_reasons_document: Trucades_3354
credential_name: drive-certificate.json
threshold_hits: 21
my_calls_log: my_calls_log.yaml
