fullIndisponibilitats: 'Reunions i altres afers' # 'oyfu0hb' # Fulla del drive on estan les indisponibilitats
fullCarrega: 'o9rxhxk' # 'Càrrega setmanal de telèfon' # Fulla del drive on estan les càrregues
intervalCarrega: carregatelefon_{:02d}{:02d}{:02d} # Patró pel nom de l'interval on buscar les càrregues (Y,m,d)
monitoringFile: taula.html

nTelefons: 4
diesCerca: ['dv', 'dm', 'dx', 'dj', 'dl',] # Els mes conflictius davant
diesVisualitzacio: ['dl','dm','dx','dj','dv']

hores:  # La darrera es per tancar
- '09:00'
- '10:15'
- '11:30'
- '12:45'
- '14:00'
mostraCami:  false   # mostra el cami de cerca que va fent (molt lent)
maximCamiAMostrar: 60   # fins a quin nivell mostra el camí de cerca
aleatori: true   # si l'ordre de provar entre els companys a cada casella es aleatori
backtrackDepth: 10000   # Comprovacions a una via abans de rendir-se i provar una altra
costLimit: 100   # No et molestis en comprobar solucions que no sigui millors
descartaNoPrometedores: true # Pot descartar solucions bones, pero agilitza molt
deixaEsmorzar: true     # Si hom ha de tenir una de les hores d'esmorzar lliures
noVolenEsmorzar:
- david
maximPerTaula: 2   # maxim nombre de telefons simultanis a una mateixa taula
maximsT1PerDia: 1   # maxim nombre de torns primaris diaris per a una persona
maximHoresDiariesGeneral: 2  # maxim nombre de torns diaris per una persona
maximHoresDiaries:   # excepcions al maximHoresDiariesGeneral
   manel: 2
   joan: 2
   silvia: 2
costHoresDiscontinues: 40   # Per cada salt que te una persona entre dos hores de telefon un mateix dia
costHoresConcentrades: 1   # Es multiplica per n·(n-1)/2 on n es el nombre d'hores diaries d'una mateixa persona
costTaulaSorollosa: 5   # Es multiplica per n·(n-1)/2 on n es el nombre de telefons simultanis a una taula
costHoraNoDesitjada: 0   # No implementat
taules: # Asignacio de les persones en taules
   marc:   0
   eduard: 1
   pere:   1
   david:  2
   aleix:  2
   cesar:  2
   carles: 3
   monica: 3
   judith: 3
   silvia: 3
   victor: 4
   erola:  4
   sergi:  4
   judit:  4
   marta:  5
   yaiza:  5
   joan:   5
   ana:    5
   jordi:  5
   manel:  6
   tania:  6
   lucia:  6
   vic:    6
sempreUnLliure: {}
randomColors: false # Si vols generar colors aleatoris o fer cas de 'colors'
colors:
   marc:   'fbe8bc'
   eduard: 'd8b9c5'
   pere:   '8f928e'
   david:  'ffd3ac'
   aleix:  'eed0eb'
   carles: 'c98e98'
   marta:  'eb9481'
   monica: '7fada0'
   yaiza:  '90cdb9'
   erola:  '8789c8'
   manel:  '88dfe3'
   tania:  'c8abf4'
   judit:  'e781e8'
   silvia: '8097fa'
   joan:   'fae080'
   ana:    'ff6600'
   victor: 'ff3333'
   jordi:  'ff9999'
extensions:
   marta:  3040
   monica: 3041
   manel:  3042
   erola:  3043
   yaiza:  3044
   eduard: 3045
   marc:   3046
   judit:  3047
   judith: 3057
   tania:  3048
   carles: 3051
   pere:   3052
   aleix:  3053
   david:  3054
   silvia: 3055
   joan:   3056
   ana:    3181
   victor: 3182
   jordi:  3183
   lucia:  3184
   vic:    3185
   sergi:  3186
noms: # Els que no només cal posar en majúscules
   silvia: Sílvia
   monica: Mònica
   tania: Tània
   cesar: César
   victor: Víctor
   lucia: Lucía

forced:
  dl:
    1:
      3: Null
    2:
      3: Null
  dm:
    1:
      3: Null
    2:
      3: Null
  dx:
    1:
      3: Null
    2:
      3: Null
  dj:
    1:
      3: Null
    2:
      3: Null
  dv:
    1:
      3: Null
    2:
      3: Null


